# This nodeset spins up a simple one-host test VM for both EL6 and EL7
HOSTS:
  nats01:
    roles:
      - default
      - master
      - middleware
      - client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 512
  server-el7:
    roles:
      - server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server-el6:
    roles:
      - server
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  ## vb_gui: true
